<?php

$produto_estoque = [
    [
        'id' => 1,
        'nome' => 'Cimento Votoran 50kg',
        'categoria' => 'bruto',
        'quantidade' => 60,
        'preco' => 36.50,
    ],
    [
        'id' => 2,
        'nome' => 'Areia Média (m³)',
        'categoria' => 'bruto',
        'quantidade' => 25,
        'preco' => 120.00,
    ],
    [
        'id' => 3,
        'nome' => 'Brita 1 (m³)',
        'categoria' => 'bruto',
        'quantidade' => 18,
        'preco' => 135.00,
    ],
    [
        'id' => 4,
        'nome' => 'Vergalhão 5/16 12m',
        'categoria' => 'bruto',
        'quantidade' => 40,
        'preco' => 48.90,
    ],
    [
        'id' => 5,
        'nome' => 'Tijolo Baiano (milheiro)',
        'categoria' => 'bruto',
        'quantidade' => 8,
        'preco' => 750.00,
    ],
    [
        'id' => 6,
        'nome' => 'Martelo de Unha Tramontina',
        'categoria' => 'ferramentas',
        'quantidade' => 12,
        'preco' => 39.90,
    ],
    [
        'id' => 7,
        'nome' => 'Furadeira Impacto 650W',
        'categoria' => 'ferramentas',
        'quantidade' => 7,
        'preco' => 189.90,
    ],
    [
        'id' => 8,
        'nome' => 'Chave de Fenda 1/4x6',
        'categoria' => 'ferramentas',
        'quantidade' => 20,
        'preco' => 12.50,
    ],
    [
        'id' => 9,
        'nome' => 'Disco de Corte para Metal 4.1/2',
        'categoria' => 'ferramentas',
        'quantidade' => 30,
        'preco' => 6.90,
    ],
    [
        'id' => 10,
        'nome' => 'Porcelanato 60x60',
        'categoria' => 'acabamento',
        'quantidade' => 90,
        'preco' => 69.90,
    ],
    [
        'id' => 11,
        'nome' => 'Rejunte Flexível 1kg',
        'categoria' => 'acabamento',
        'quantidade' => 50,
        'preco' => 8.90,
    ],
    [
        'id' => 12,
        'nome' => 'Tinta Acrílica Branca 18L',
        'categoria' => 'acabamento',
        'quantidade' => 10,
        'preco' => 229.90,
    ],
    [
        'id' => 13,
        'nome' => 'Rolo de Pintura 23cm',
        'categoria' => 'acabamento',
        'quantidade' => 25,
        'preco' => 14.90,
    ],
    [
        'id' => 14,
        'nome' => 'Cano PVC 100mm 6m',
        'categoria' => 'hidraulica',
        'quantidade' => 22,
        'preco' => 89.90,
    ],
    [
        'id' => 15,
        'nome' => 'Registro de Pressão 1/2',
        'categoria' => 'hidraulica',
        'quantidade' => 15,
        'preco' => 32.00,
    ],
    [
        'id' => 16,
        'nome' => 'Caixa d\'água 1000L',
        'categoria' => 'hidraulica',
        'quantidade' => 5,
        'preco' => 499.00,
    ],
    [
        'id' => 17,
        'nome' => 'Fio Elétrico 2,5mm (rolo 100m)',
        'categoria' => 'eletrica',
        'quantidade' => 14,
        'preco' => 289.90,
    ],
    [
        'id' => 18,
        'nome' => 'Disjuntor 20A',
        'categoria' => 'eletrica',
        'quantidade' => 35,
        'preco' => 18.90,
    ],
    [
        'id' => 19,
        'nome' => 'Tomada Dupla 10A',
        'categoria' => 'eletrica',
        'quantidade' => 40,
        'preco' => 9.90,
    ],
    [
        'id' => 20,
        'nome' => 'Interruptor Simples',
        'categoria' => 'eletrica',
        'quantidade' => 38,
        'preco' => 7.50,
    ],
];